server.port=${PORT:8080}

weather.api.key=${WEATHER_API_KEY:4b95b661cd6e31f19e99b0788ff4a19d}
weather.api.base-url=https://api.openweathermap.org/data/2.5

logging.level.com.weather=DEBUG
logging.level.org.springframework.web=INFO